# Generated by Django 5.1.4 on 2025-01-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=600)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('ticket_required', models.BooleanField(blank=True, default=False, null=True)),
                ('ticket_url', models.URLField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
