# Generated by Django 5.1.4 on 2025-02-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(default='no-image.svg', upload_to='media/event-images/'),
        ),
    ]
