# Generated by Django 5.1.4 on 2025-01-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='permanently_unavailable',
            field=models.BooleanField(default=False, help_text='Mark this product as unavailable for sale.'),
        ),
    ]
